config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get  '/help',       to: 'static_pages#help'
  get  '/about',      to: 'static_pages#about'
  get  '/contact',    to: 'messages#new', as: 'contact'
  post '/contact',    to: 'messages#create'
  get  '/signup',     to: 'users#new'
  post '/signup',     to: 'users#create'
  get  '/login',      to: 'sessions#new'
  post '/login',      to: 'sessions#create'
  delete '/logout',   to: 'sessions#destroy'
  post '/users/:id',  to: 'users#make_admin', as: 'make_admin'
  post '/teams/teamtext', to: 'teams#teamtext'
  resources :users
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :players
  resources :teams
  resources :games
  resources :posts do
    resources :comments
  end

  resources :comments do
    resources :comments
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    if logged_in?
      @post = current_user.posts.build
      @feed_items = current_user.feed
    else
      @feed_items = Post.select { |post| post.public == true }
    end
  end

  def help
  end

  def about
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.erb
<% content_for :title, "About" %>
<h1>About</h1>

<p>
  Santa Barbara Cuervos Football Club is an amateur soccer team created by Joshua
  Noeggerath with the objective of providing a fun soccer experience for children. While
  the kids are doing physical activities, they also learn how to work together as a team
  to achieve a common goal.
</p>

<p>
  SB Cuervos FC englobes 5 different rosters of children from Under 7 years old
  up to 11 years old, as well as an adults team.
</p>

<p>
  This <a href='/'>web application</a> was created to share the news about
  the amateur soccer team SB Cuervos FC and a tool for the communication between
  coaches and players.
  Here, parents and children can follow the news of SB Cuervos FC and the coaches
  can communicate to all the different rosters easily. The application provides
  a way for coaches to instant message all players of a roster for any immediate
  communication.
</p>

<p>
  For more information about the tournaments that SB Cuervos FC adult roster is
  involved please check the <a href="http://santabarbaraccsl.com/">Santa Barbara
  CCSL website</a>.
  We will have more information about the children rosters tournaments soon.
</p>


Other links for the adult category:
<ul>
  <li><a href="http://santabarbaraccsl.com/standings-2/">Winter Division Standings</a></li>
  <li><a href="http://santabarbaraccsl.com/team/sb-cuervos-fc/">SB Cuervos FC</a> Profile</li>
</ul>

app/views/static_pages/help.html.erb
<% content_for :title, "Help" %>
<h1>Help</h1>

<p>
  If you need to contact <em>Nelson Dornelas</em>, author of the app, send an email to:
  please use the contact form on the bottom right of the website.
</p>

<p>
  To get help on the Ruby on Rails tutorial at the
  <a href="http://www.railstutorial.org/help">Rails Tutorial help page</a>.
   To get help on this sample app, see the
  <a href="http://www.railstutorial.org/book"><em>Ruby on Rails Tutorial</em>
  book</a>.
</p>

app/views/static_pages/home.html.erb
<% if logged_in? %>
  <div class='row'>
    <div class='col-xs-8 col-xs-offset-2 col-sm-8 col-sm-offset-2 col-md-6 col-md-offset-3 col-lg-6 col-lg-offset-3'>
      <h1>News</h1>
      <%= link_to "New post", new_post_path %>
      <%= render 'shared/feed' %>
    </div>
  </div>
<% else %>
<div class='center'>
    <%= image_tag('cuervos_badge.png', height: 300, width: 250) %>
  <br/><br/>
    Don't have an account? <strong><%= link_to "Sign up now!", signup_path%></strong>
</div>
<div class="row">
  <div class='col-xs-8 col-xs-offset-2 col-sm-8 col-sm-offset-2 col-md-6 col-md-offset-3 col-lg-6 col-lg-offset-3'>
    <h1>News</h1>
    <%= render 'shared/feed' %>
  </div>
</div>
<% end %>